### ISSUE TITLE
what is this? :D

### ISSUE THREAD

**Issue by EGOIST1372** [IMS212/NVIDIAFix#1]
and fixes what? I'm just curious

**Comment by bczhc** [comment]
> and fixes what? I'm just curious

The latest Nvidia driver bug, causing Minecraft Optifine shaders buggy, like some weird stripes etc.

You can refer to these links:
https://github.com/sp614x/optifine/issues/6849
https://www.reddit.com/r/Optifine/comments/v93m97/broken_shadows_and_generally_glitchy_shaders/
https://www.reddit.com/r/linuxquestions/comments/v921a4/arch_broken_shadows_using_optifine_on_minecraft/

**Comment by EGOIST1372** [comment]
thanks for the info
